version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/task_manager:cached
    ports:
      - 3000:3000
    volumes_from:
      - bundle_cache
    environment:
      - BUNDLE_PATH=/bundle_cache
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
  db:
    image: postgres:10.3-alpine
  ci:
    build: .
    depends_on:
      - db
    environment:
      - COVERAGE
      - RAILS_ENV
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
    command: sh -c "bundle exec rails webpacker:install && bundle exec rails db:create db:migrate && bundle exec rake test"
  bundle_cache:
    image: busybox
    volumes:
      - /bundle_cache
